server/forms.py
__author__ = 'Alimohammad'

from wtforms import Form, StringField, PasswordField, validators, BooleanField

from flask import current_app

import urllib
import urllib2
import json

class LoginForm(Form):
    email = StringField('Email Address', [validators.email(message=u'Invalid email address')])
    password = PasswordField('Password', [validators.DataRequired(message=u'Password required')])
    remember = BooleanField('Remember Me')

server/main.py
__author__ = 'Alimohammad'

from flask import Flask, render_template
from flask_login import LoginManager
import json
import logging

from views.common_views import common_views
from views.user_views import user_views
from views.admin_views import admin_views
from data_model import User
from werkzeug.contrib.fixers import ProxyFix

app = Flask(__name__)
app.wsgi_app = ProxyFix(app.wsgi_app)
app.register_blueprint(common_views)
app.register_blueprint(user_views)
app.register_blueprint(admin_views)
app.config["custom_config"] = json.loads(open("config.json").read())

app.secret_key = app.config["custom_config"]["secret_key"]

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "common_views.index"


@login_manager.user_loader
def load_user(user_id):
    return User.get(user_id)


@app.errorhandler(403)
def forbidden(e):
    return render_template('403.html'), 403

@app.errorhandler(404)
def forbidden(e):
    return render_template('404.html'), 404

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')

server/views/__init__.py
__author__ = 'Alimohammad'

server/views/admin_views.py
__author__ = 'Alimohammad'
from flask import request, render_template, abort, url_for, redirect
from flask_login import login_required, current_user
from data_model import Device, User
from functools import wraps
from flask import Blueprint

import datetime

admin_views = Blueprint('admin_views', __name__, template_folder='templates')


def admin_required(main_function):
    @wraps(main_function)
    def new_function(*args, **kwargs):
        if current_user.role != "admin":
            abort(403)
        else:
            return main_function(*args, **kwargs)
    return new_function

@admin_views.route('/admin/')
@login_required
@admin_required
def index():
    return render_template("admin/admin_index.html")


@admin_views.route('/admin/devices/')
@login_required
@admin_required
def devices_view():
    devices = Device.find_all_devices()
    return render_template("admin/admin_devices.html", devices=devices)


@admin_views.route('/admin/device/<device_id>/')
@login_required
@admin_required
def device_view(device_id):
    device = current_user.get_device(device_id)
    if device is not None:
        device_owner = User.get(user_id=device.device_owner)
        return render_template("admin/admin_device.html", device=device, device_owner=device_owner)
    else:
        abort(403)

server/views/common_views.py
__author__ = 'Alimohammad'
from flask import redirect, url_for, request, render_template, abort
from flask_login import login_user, login_required, current_user, logout_user
from flask import current_app

from data_model import User
from forms import LoginForm

from flask import Blueprint

common_views = Blueprint('common_views', __name__, template_folder='templates')

@common_views.route('/', methods=["GET", "POST"])
def index():
    form = LoginForm(request.form)
    error = None
    if request.method == 'POST' and form.validate():
        user = User.get(email=form.email.data)
        if user is not None:
            if user.authenticate(form.password.data):
                if login_user(user, remember=True):
                    current_app.logger.debug(url_for("user_views.devices_view"))
                    return redirect(request.args.get("next") or url_for("user_views.devices_view"))
            else:
                error = "Email and password do not match!"
        else:
            error = "A user with this email does not exist!"
    return render_template("index.html", form=form, error=error)

@common_views.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for("common_views.index"))

server/views/user_views.py
__author__ = 'Alimohammad'
from flask import request, render_template, abort, url_for, redirect
from flask_login import login_required, current_user
import datetime
import json
from urlparse import urlparse, urljoin

from flask import Blueprint

user_views = Blueprint('user_views', __name__, template_folder='templates')


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

@user_views.route('/devices/')
@login_required
def devices_view():
    devices = current_user.find_devices()
    return render_template("users/devices.html", devices=devices)


@user_views.route('/device/<device_id>/')
@login_required
def device_view(device_id):
    device = current_user.get_device(device_id)
    past_samples = device.get_past_samples()
    if device is not None:
        return render_template("users/device.html", device=device, past_samples=past_samples)
    else:
        abort(403)

@user_views.route('/device/<device_id>/send_sampling_request/')
@login_required
def request_sample(device_id):
    device = current_user.get_device(device_id)
    if device is not None:
        duration = int(request.args.get("duration"))
        duration = min(duration, 60)
        duration = max(duration, 5)
        result = device.request_sampling(duration)
        return json.dumps(result)
    abort(403)

@user_views.route('/device/<device_id>/timeseries/')
@login_required
def device_get_timeseries(device_id):
    sample_id = request.args.get("sample_id")
    device = current_user.get_device(device_id)
    if device is not None:
        data = device.get_pressure_timeseries_data(sample_id)
        return json.dumps(data)
    else:
        abort(403)

@user_views.route('/device/<device_id>/fft/')
@login_required
def device_get_fft(device_id):
    sample_id = request.args.get("sample_id")
    device = current_user.get_device(device_id)
    if device is not None:
        data = device.get_fft_data(sample_id)
        return json.dumps(data)
    else:
        abort(403)

@user_views.route('/device/<device_id>/get_occupancy_temperature_list/')
@login_required
def device_get_occupancy_temperature_list(device_id):
    device = current_user.get_device(device_id)
    occupancy_temperature_list = None
    if device is not None:
        if request.args.get("time_interval") == "Month":
            occupancy_temperature_list = device.get_occupancy_temperature_list(datetime.datetime.utcnow() + datetime.timedelta(weeks=-4))
        elif request.args.get("time_interval") == "Week":
            occupancy_temperature_list = device.get_occupancy_temperature_list(datetime.datetime.utcnow() + datetime.timedelta(weeks=-1))
        elif request.args.get("time_interval") == "Day":
            occupancy_temperature_list = device.get_occupancy_temperature_list(datetime.datetime.utcnow() + datetime.timedelta(days=-1))
        elif request.args.get("time_interval") == "Hour":
            occupancy_temperature_list = device.get_occupancy_temperature_list(datetime.datetime.utcnow() + datetime.timedelta(hours=-1))
        elif request.args.get("time_interval") == "Now":
            occupancy_temperature_list = device.get_occupancy_temperature_list(datetime.datetime.utcnow() + datetime.timedelta(minutes=-15))
        elif request.args.get("time_interval") == "Last":
            occupancy_temperature_list = device.get_last_occupancy_temperature()
        return json.dumps(occupancy_temperature_list)
    else:
        abort(403)


@user_views.route('/device/<device_id>/start_training/')
@login_required
def start_training(device_id):
    device = current_user.get_device(device_id)
    if device is not None:
        device.start_training()
        if is_safe_url(request.referrer):
            return redirect(request.referrer)
        else:
            return redirect(url_for("user_views.device_view", device_id=device.device_id))
    abort(403)

@user_views.route('/device/<device_id>/submit_vote/')
@login_required
def submit_vote(device_id):
    device = current_user.get_device(device_id)
    if device is not None:
        if device.submit_vote(int(request.args.get("value"))):
            return "ok"
    abort(403)

@user_views.route('/device/<device_id>/end_training/')
@login_required
def end_training(device_id):
    device = current_user.get_device(device_id)
    if device is not None:
        device.end_training()
        if is_safe_url(request.referrer):
            return redirect(request.referrer)
        else:
            return redirect(url_for("user_views.device_view", device_id=device.device_id))
    abort(403)

server/templates/_formhelpers.html
{% macro render_login_text(field) %}
<div class="form-group {% if field.errors %} error {% endif %}">
    {{ field(class='form-control', placeholder=field.label.text)| safe }}
</div>
{% endmacro %}}

{% macro render_recaptcha() %}
    <div class="g-recaptcha form-group" data-sitekey="6LeOyxUTAAAAAA8O9SwC6Z8COSLiKAYRyHiopeUD"></div>
{% endmacro %}}

{% macro render_change_pass(field) %}
<div class="form-group">
    {{ field(class='form-control', placeholder=field.label.text)| safe }}
    {% if field.errors %}
    {% for error in field.errors %}
    <p class="text-danger" style="margin-top:5px;">
        <strong>{{ error }}</strong>
    </p>
    {% endfor %}
    {% endif %}
</div>
{% endmacro %}}


{% macro render_login_check(field) %}
<div class="form-group">
    <label class="checkbox" style="color:white; margin-top:-7px; padding-left: 5px;">
        <small>{{ field.label.text }}</small><br/>
        {{ field(style="margin-left:35px;")|safe }}
    </label>
</div>
{% endmacro %}}

server/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="WatSmart">
    <meta name="author" content="Alimohammad Rabbani">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-16x16.png') }}" sizes="16x16">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-24x24.png') }}" sizes="24x24">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-48x48.png') }}" sizes="48x48">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-64x64.png') }}" sizes="64x64">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-96x96.png') }}" sizes="96x96">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-128x128.png') }}" sizes="128x128">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-256x256.png') }}" sizes="256x256">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-512x512.png') }}" sizes="512x512">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='icons/spotstar-32x32.png') }}" sizes="32x32">


    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/slider.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{{ url_for('static', filename='js/ie8-responsive-file-warning.js')}}"></script><![endif]-->
    <script src="{{ url_for('static', filename='js/ie-emulation-modes-warning.js')}}"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <title>WatSmart - {% block title %}{% endblock %}</title>
</head>
<body id="page-top" data-spy="scroll" data-target="#sidenav">
<a class="anchor" id="top"></a>
<div id="wrap">
    {%include 'navbar.html' %}
    {% block content %}{% endblock %}
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap-slider.js')}}"></script>
    <div id="push"></div>
</div>
{%include 'footer.html' %}
{% block body_bottom %}{% endblock %}
</body>
</html>

server/templates/device/fft.html
<script>
$(document).ready(function() {
    for(var i = 1; i <= {{ past_samples | length }}; i++) {
        $('#fftGraphLink' + i).click(function(e) {
            update_fft_graph($(this).attr('sample_id'));
            e.preventDefault();
        });
    }
    var fftData = [];

    initialize_fft_graph("{{ past_samples[0]['sample_id'] }}");

    function initialize_fft_graph(sample_id) {
        $.get( "{{ url_for('user_views.device_get_fft', device_id=device.device_id) }}", {sample_id: sample_id})
        .success(function(data) {
            fftData = eval(data);
            $('#fftChart').highcharts({
                chart: {
                    zoomType: 'x',
                    type: 'line',
                    alignTicks: false
                },
                credits: {enabled: false},
                title: {text: ''},
                xAxis: {title: {text: "Frequency (Hz)"}, min: 0, max:100, tickInterval: 10},
                yAxis: {min: 0},
                legend: {enabled: false},
                plotOptions: {line: {lineWidth: 2}},
                series: [{type: 'line', color: '#D80030', name: 'FFT', data: fftData}]
            });
        })
        .fail(function() {
            alert("network fail");
        });
    }
    function update_fft_graph(sample_id) {
        $('#fftChart').highcharts().destroy();
        initialize_fft_graph(sample_id)
	}
});
</script>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">FFT Graph</h3>
            </div>
            <div class="panel-body">
                <div class="row" style="padding-left:10px;">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="fftChart" style="height: 200px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>

server/templates/device/info.html
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Device Information</h3>
            </div>
            <div class="panel-body">
                <div class="row" style="padding-left:20px; padding-right:25px;">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="well" style="margin-bottom: 0px;">
                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4"><strong>IP:</strong></div>
                                <div class="col-lg-10 col-md-9 col-sm-9 col-xs-8">{{ device.device_ip }}</div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4"><strong>Location:</strong></div>
                                <div class="col-lg-10 col-md-9 col-sm-9 col-xs-8">{{ device.device_location }}</div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4"><strong>Mac Address:</strong></div>
                                <div class="col-lg-10 col-md-9 col-sm-9 col-xs-8">{{ device.device_mac }}</div>
                            </div>
                            <div class="row">
                                <div class="col-lg-2 col-md-3 col-sm-3 col-xs-4"><strong>Latest Update:</strong></div>
                                <div class="col-lg-10 col-md-9 col-sm-9 col-xs-8">{% if device.latest_update_time %}{{ device.latest_update_time.strftime("%Y-%b-%d %H:%M:%S %Z") }}{% else %}None{% endif %}</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

server/templates/device/past_samples.html
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Past Samples</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered" style="margin-bottom:0px;">
                    <tr>
                        <th>Timestamp</th>
                        <th>ID</th>
                        <th>Duration</th>
                        <th>RAW</th>
                        <th>Timeseries</th>
                        <th>FFT</th>
                    </tr>
                {% for sample in past_samples %}
                    <tr>
                        <td>{{ sample["timestamp"] }}</td>
                        <td>{{ sample["sample_id"] }}</td>
                        <td>{{ sample["duration"] }} seconds</td>
                        <td><a href="{{ sample['raw_url'] }}">Link</a></td>
                        <td><a href="#" id="pressureGraphLink{{ loop.index }}" sample_id="{{ sample['sample_id'] }}">Visualize</a></td>
                        <td><a href="#" id="fftGraphLink{{ loop.index }}" sample_id="{{ sample['sample_id'] }}">Visualize</a></td>
                    </tr>
                {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

server/templates/device/pressure_timeseries.html
<script>
$(document).ready(function() {
    for(var i = 1; i <= {{ past_samples | length }}; i++) {
        $('#pressureGraphLink' + i).click(function(e) {
            update_pressure_graph($(this).attr('sample_id'));
            e.preventDefault();
        });
    }

    var d = new Date();
    var timezoneOffset = d.getTimezoneOffset();
    Highcharts.setOptions({
        global: {
            timezoneOffset: timezoneOffset
        }
    });

    var pressureData = [];

    initialize_pressure_graph("{{ past_samples[0]['sample_id'] }}");

    function initialize_pressure_graph(sample_id) {
        $.get( "{{ url_for('user_views.device_get_timeseries', device_id=device.device_id) }}", {sample_id: sample_id})
        .success(function(data) {
            pressureData = eval(data);
            $('#pressureChart').highcharts({
                chart: {
                    zoomType: 'x',
                    type: 'line',
                    alignTicks: false
                },
                credits: {enabled: false},
                title: {text: ''},
                xAxis: {title: {text: "Time (milliseconds)"}, minRange: 5000, min: 0},
                yAxis: {title: {text: 'Pressure (Pa)'}, min: 0},
                legend: {enabled: false},
                plotOptions: {line: {lineWidth: 2}},
                series: [{type: 'line', color: '#19D11C', name: 'Pressure', data: pressureData}]
            });
        })
        .fail(function() {
            alert("network fail");
        });
    }
    function update_pressure_graph(sample_id) {
        $('#pressureChart').highcharts().destroy();
        initialize_pressure_graph(sample_id)
	}
});
</script>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Pressure Timeseries</h3>
            </div>
            <div class="panel-body">
                <div class="row" style="padding-left:10px;">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="pressureChart" style="height: 200px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>

server/templates/device/start_sampling.html
<script type='text/javascript'>
$(document).ready(function() {
    $("#duration-slider").slider()
    $("#duration-button").click(function() {
        $.get( "{{ url_for('user_views.request_sample', device_id=device.device_id) }}", "duration=" + $("#duration-slider").val(), function(result) {})
        .success(function(data) {
            result = eval(data)
            $("#samplingAlert").hide();
            $("#samplingAlert").html(result[1])
            if (result[0] == 0) {
                $("#samplingAlert").attr('class', 'alert alert-success');
            } else {
                $("#samplingAlert").attr('class', 'alert alert-warning');
            }
            $("#samplingAlert").fadeIn(1000);
        })
        .fail(function(data) {
            $("#samplingAlert").hide();
            $("#samplingAlert").attr('class', 'alert alert-danger');
            $("#samplingAlert").html('<strong>Warning!</strong> There was a problem sending the request!')
            $("#samplingAlert").fadeIn(1000);
        });
    });
});
</script>
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Start Sampling</h3>
            </div>
            <div class="panel-body">
                <div class="row" style="margin-left: 15px; margin-right: 15px;">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-top:10px;">
                        You can make this device start sampling here. Simply choose a duration for sampling, and submit the request.
                        While the sampling is performed, you cannot submit another sampling request. When sampling is finished, you can
                        see the result in the "Past Samples" panel if you refresh.
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" style="margin-top:10px;">
                        <div class="well">
                            <div class="row" style="margin-bottom: 10px; margin-left:5px; margin-right:5px;"><strong>Sampling Duration</strong> (seconds):</div>
                            <div class="row" style="margin-bottom: 20px; margin-left:5px; margin-right:5px;">
                                <input id="duration-slider" data-slider-id='offsetSlider' data-slider-min="5" data-slider-max="60" data-slider-step="5" data-slider-value="10"/>
                            </div>
                            <div class="row" style="margin-left:5px; margin-right:5px;">
                                <a id="duration-button" class="btn btn-danger center-block">Submit Sampling Request</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="text-align:center;">
                        <div class="alert alert-success" id="samplingAlert" style="display:none; margin-bottom:0; margin-top:15px;">
                            <strong>Warning!</strong> There was a problem sending the request!
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

server/templates/footer.html
<div id="footer">
    <div class="container">
        <p class="text-muted text-center credit">All rights reserved for <a href="http://iss4e.ca">ISS4E Lab</a>. Designed and created by <a href="http://onible.com/">Alimohammad Rabbani</a>.</p>
    </div>
</div>

server/templates/index.html
{% extends "base.html" %}
{% block title %}My Comfort Management Tool{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_login_text %}
{% from "_formhelpers.html" import render_login_check %}
<div class="jumbotron" style="padding-top:30px; padding-bottom:25px;">
    {% if error %}
    <div class="alert alert-danger text-center">
        {{ error }}
    </div>
    {% endif %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <p>
                    <strong>WatSmart</strong>
                    <small>
                        Detects leaks in water mains, saving hundreds of thousands of dollars every year.
                    </small>
                </p>
                <p class="text-warning">
                    <strong><small>To learn more about WatSmart, please click here.</small></strong>
                </p>
            </div>
            <div class="col-lg-5 col-md-6 col-lg-offset-1">
                <img src="{{ url_for('static', filename='images/sonar_box_small.jpg')}}" alt="WatSMart Box" class="img-thumbnail">
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Who is doing this?</h3>
            <p>
                The Structural Dynamics, Control & Identification Group at the University of Waterloo started the WatSmart project.
                It is supervised by <a href="http://blizzard.cs.uwaterloo.ca/keshav/">Prof. Narasimhan</a>, and currently,
                Roya Cody, Alimohammad Rabbani, and Costin Ograda-Bratu
                are involved in the project.
            </p>
        </div>
        <div class="col-md-4">
            <h3>What is this website for?</h3>
            <p>
                This website is created primarily for WatSMart users to control the devices and collect data from them.
                After samples are collected it provides the user with visualizations of water leaks.
                In addition, it provides admin tools to monitor the deployment.
                The website also provides a brief description of WatSmart for people who are interested in this area of research.
            </p>
        </div>
        <div class="col-md-4">
            <h3>How can I help?</h3>
            <p>
                If you find yourself interested in this project, you can always contact us
                at <a href="mailto:sriram.narasimhan@uwaterloo.ca"> sriram.narasimhan@uwaterloo.ca</a>. We are looking forward to
                your comments and suggestions and will be more than happy to have you on board if you are interested.
            </p>
        </div>
    </div>
</div> <!-- /container -->
{% endblock %}

server/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
{% from "_formhelpers.html" import render_login_text %}
{% from "_formhelpers.html" import render_login_check %}
<div class="container">
</div><!-- /.container -->
{% endblock %}

{% block body_bottom %}
{% endblock %}

server/templates/navbar.html
{% from "_formhelpers.html" import render_login_text %}
{% from "_formhelpers.html" import render_login_check %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse navbar-left">
            <ul class="nav navbar-nav">
                <li{% if request.path == url_for('common_views.index') %} class="active"{% endif %}>
                    <a href="{{ url_for('common_views.index') }}">WatSmart* Home</a>
                </li>
            </ul>
        </div>
        {% if current_user.is_authenticated %}
        <div class="navbar-collapse collapse navbar-right" style="margin-top: 7px;">
            <div class="btn-group">
                <button type="button" class="btn btn-primary">{{ current_user.name }}</button>
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{{ url_for('common_views.index') }}">Home</a></li>
                    {% if current_user.role == "admin" %}
                    <li class="divider"></li>
                    <li><a href="{{ url_for('admin_views.devices_view') }}">God Mode!</a></li>
                    {% endif %}
                    <li class="divider"></li>
                    <li><a href="{{ url_for('user_views.devices_view') }}">My Devices</a></li>
                    <li><a href="#">My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('common_views.logout') }}">Log me out</a></li>
                </ul>
            </div>
        </div>
        {% elif form %}
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-right" role="form" method=post action="{{ url_for('common_views.index') }}">
                {{ render_login_text(form.email) }}
                {{ render_login_text(form.password) }}
                <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;"/>
            </form>
        </div><!--/.navbar-collapse -->
        {% endif %}
    </div>
</nav>

server/templates/users/device.html
{% extends "base.html" %}
{% block title %}{{ device.device_location }}{% endblock %}
{% block content %}
<div class="container" style="padding-top:20px;">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="{{ url_for('common_views.index') }}">Home</a></li>
                <li><a href="{{ url_for('user_views.devices_view') }}">Devices</a></li>
                <li class="active">{{ device.device_location }}</li>
            </ol>
        </div>
    </div>
    {% include 'device/info.html' %}
    {% include 'device/start_sampling.html' %}
    {% if past_samples | length > 0 %}
    {% include 'device/pressure_timeseries.html' %}
    {% include 'device/fft.html' %}
    {% endif %}
    {% include 'device/past_samples.html' %}
</div>
{% endblock %}
{% block body_bottom %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
{% endblock %}